basePath: /
definitions:
  models.Book:
    properties:
      UUID:
        type: string
      name:
        type: string
    type: object
  models.Customer:
    properties:
      UUID:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
    type: object
  models.Order:
    properties:
      UUID:
        type: string
      size:255;:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: Gt Web API
  title: Gt API
  version: 0.0.1
paths:
  /books:
    get:
      description: Endpoint to retrieve all books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Book'
            type: array
      summary: Retrieve entire books inventory
      tags:
      - Book
  /customers:
    post:
      description: Endpoint to post customer creation
      parameters:
      - description: First Name
        in: body
        name: firstName
        required: true
        schema:
          type: string
      - description: Last Name
        in: body
        name: lastName
        required: true
        schema:
          type: string
      - description: Email
        in: body
        name: email
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Customer'
      summary: Create customer
      tags:
      - Customer
  /customers/{customerUUID}:
    get:
      description: Endpoint to retrieve customer record
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Customer'
      summary: Show sole customer by id or email
      tags:
      - Customer
  /customers/{customerUUID}/orders:
    get:
      description: Endpoint to retrieve customer record
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Order'
            type: array
      summary: Retrieve all orders / order history for particular customer
      tags:
      - Customer
  /customers/{customerUUID}/orders/{orderUUID}:
    get:
      description: Endpoint to retrieve order record
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Order'
      summary: Retrieve order details
      tags:
      - Order
  /ping:
    get:
      description: Endpoint to check for a basic response
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Basic health check
      tags:
      - Ping
swagger: "2.0"
